# Generated by Django 6.0.2 on 2026-02-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=180)),
                ('text', models.TextField()),
                ('title', models.CharField(max_length=180)),
                ('decription', models.TextField()),
                ('btn_text', models.CharField(max_length=60)),
            ],
        ),
    ]
