# Generated by Django 6.0.2 on 2026-02-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_scratchlesson_scratchcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scratchcourse',
            name='heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scratchcourse',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scratchcourse',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
