# Generated by Django 6.0.2 on 2026-02-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_scratchcourse_heading_alter_scratchcourse_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScratcLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='scratchcourse',
            name='lessons',
        ),
        migrations.RemoveField(
            model_name='scratchcourse',
            name='heading',
        ),
        migrations.AddField(
            model_name='scratchcourse',
            name='btn_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='ScratchLesson',
        ),
    ]
