# Generated by Django 6.0.2 on 2026-02-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_scratclesson_remove_scratchcourse_lessons_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_id', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True)),
                ('btn_text', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField(blank=True)),
                ('quiz', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LessonContentFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('lessons', models.ManyToManyField(related_name='courses', to='quiz.lessoncontent')),
            ],
        ),
    ]
