# Generated by Django 6.0.2 on 2026-02-10 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_lessoncontent_lessoncontentfields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessoncontent',
            name='btn_text',
        ),
        migrations.RemoveField(
            model_name='lessoncontent',
            name='text',
        ),
    ]
