# Generated by Django 6.0.2 on 2026-02-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_remove_lessoncontent_btn_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessoncontent',
            name='lesson_id',
        ),
        migrations.AlterField(
            model_name='lessoncontent',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lessoncontent',
            name='quiz',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='LessonContentFields',
        ),
    ]
